from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

REQUIRED_REVIEW_FILES = [
    "README.md",
    "requirements.txt",
    "notebooks/01_model_training.ipynb",
    "notebooks/02_demand_policy_scenarios.ipynb",
    "notebooks/03_carbon_emissions_analysis.ipynb",
    "notebooks/executed/01_model_training_executed.ipynb",
    "notebooks/executed/02_demand_policy_scenarios_executed.ipynb",
    "notebooks/executed/03_carbon_emissions_analysis_executed.ipynb",
    "notebooks/executed/04_figure_generation_executed.ipynb",
    "data/README.md",
    "data/carbon/neso_historic_generation_mix.csv",
    "data/metadata/informations_households.csv",
    "data/metadata/weather_hourly_darksky.csv",
    "data/metadata/weather_daily_darksky.csv",
    "data/metadata/uk_bank_holidays.csv",
    "data/metadata/acorn_details.csv",
    "models/lgbm_hh.txt",
    "models/lgbm_hh_features.json",
    "models/lstm_hh.keras",
    "models/lstm_hh_features.json",
    "results/scenario_emissions_results.csv",
    "results/scenario_emissions_chart.png",
    "results/notebook_figures/README.md",
    "docs/GOOGLE_DRIVE_DOCUMENTS.md",
]

FULL_RERUN_INPUTS = [
    "data/raw/smart_meter_data/halfhourly_dataset/halfhourly_dataset/block_0.csv",
    "data/raw/smart_meter_data/daily_dataset/daily_dataset/block_0.csv",
    "data/raw/smart_meter_data/hhblock_dataset/hhblock_dataset/block_0.csv",
    "data/raw/smart_meter_data/daily_dataset.csv",
]

DERIVED_OUTPUTS = [
    "data/processed/features_sample500.parquet",
    "results/policy_scenario_lightgbm_summary.csv",
    "results/policy_scenario_lightgbm_adequacy.csv",
    "results/policy_scenario_lightgbm_group_summary.csv",
]


def report(paths: list[str], label: str) -> bool:
    print(f"\n{label}")
    print("-" * len(label))
    missing = []
    for rel_path in paths:
        path = ROOT / rel_path
        status = "ok" if path.exists() else "missing"
        print(f"{status:8} {rel_path}")
        if not path.exists():
            missing.append(rel_path)
    return not missing


def main() -> int:
    review_ok = report(REQUIRED_REVIEW_FILES, "Required review files")
    raw_ok = report(FULL_RERUN_INPUTS, "Raw inputs for full rerun")
    derived_ok = report(DERIVED_OUTPUTS, "Generated outputs from full rerun")

    print("\nSummary")
    print("-------")
    if review_ok:
        print("The cleaned repository files needed for review are present.")
    else:
        print("Some review files are missing.")

    if raw_ok:
        print("Raw data files are available for a full rerun.")
    else:
        print("Raw data files are not tracked; see data/README.md before a full rerun.")

    if derived_ok:
        print("Derived feature/scenario outputs are present.")
    else:
        print("Some derived outputs are absent and can be regenerated by running the notebooks.")

    return 0 if review_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
